[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
structs = { workspace = true }
log = { version = "0.4", optional = true }

[build-dependencies]
regex = "1.8.5"
xmas-elf = "0.9.0"
include_bytes_aligned = "0.1.4"

[features]
log = ["dep:log"]
default = []
